# Generated by Django 5.1.6 on 2025-02-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerhub_features', '0003_userquestion_is_favorite_userresume_userroadmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroadmap',
            name='last_accessed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
